name: firebase_storage_offline
description: The flutter_firebase_storage_offline plugin is a powerful Flutter package that enhances the offline capabilities of Firebase Cloud Storage in your Flutter applications. With this plugin, you can seamlessly manage file uploads, downloads, and synchronization with Firebase Cloud Storage, even when the device is offline.
version: 0.0.1
homepage: https://github.com/cylyl/flutter_firebase_storage_offline

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_storage: ^11.0.15
  path_provider: ^2.0.13
  flutter:
    sdk: flutter
  cross_file: ^0.3.3+4
  path: ^1.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

